namespace GISCore.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class v1 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.tbAlocacao", "IDContrato", "dbo.tbContrato");
            DropForeignKey("dbo.tbAlocacao", "IDEmpregado", "dbo.tbEmpregado");
            DropForeignKey("dbo.tbContrato", "IDDepartamento", "dbo.tbDepartamento");
            DropForeignKey("dbo.tbContrato", "IDFornecedor", "dbo.tbFornecedor");
            DropForeignKey("dbo.tbDepartamento", "IDEmpresa", "dbo.tbEmpresa");
            DropForeignKey("dbo.tbEmpregado", "IDEmpresa", "dbo.tbEmpresa");
            DropForeignKey("dbo.tbEmpregado", "IDFornecedor", "dbo.tbFornecedor");
            DropForeignKey("dbo.tbEmpresaFornecedor", "IDEmpresa", "dbo.tbEmpresa");
            DropForeignKey("dbo.tbEmpresaFornecedor", "IDFornecedor", "dbo.tbFornecedor");
            DropForeignKey("dbo.tbPerfilMenu", "IDMenu", "dbo.tbMenu");
            DropForeignKey("dbo.tbPerfilMenu", "IDPerfil", "dbo.tbPerfil");
            DropForeignKey("dbo.tbUsuario", "IDDepartamento", "dbo.tbDepartamento");
            DropForeignKey("dbo.tbUsuario", "IDEmpresa", "dbo.tbEmpresa");
            DropForeignKey("dbo.tbUsuarioPerfil", "IDPerfil", "dbo.tbPerfil");
            DropForeignKey("dbo.tbUsuarioPerfil", "IDUsuario", "dbo.tbUsuario");
            DropForeignKey("dbo.tbMenu", "MenuSuperior_IDMenu", "dbo.tbMenu");
            DropIndex("dbo.tbAlocacao", new[] { "IDEmpregado" });
            DropIndex("dbo.tbAlocacao", new[] { "IDContrato" });
            DropIndex("dbo.tbContrato", new[] { "IDFornecedor" });
            DropIndex("dbo.tbContrato", new[] { "IDDepartamento" });
            DropIndex("dbo.tbDepartamento", new[] { "IDEmpresa" });
            DropIndex("dbo.tbEmpregado", new[] { "IDEmpresa" });
            DropIndex("dbo.tbEmpregado", new[] { "IDFornecedor" });
            DropIndex("dbo.tbEmpresaFornecedor", new[] { "IDEmpresa" });
            DropIndex("dbo.tbEmpresaFornecedor", new[] { "IDFornecedor" });
            DropIndex("dbo.tbPerfilMenu", new[] { "IDPerfil" });
            DropIndex("dbo.tbPerfilMenu", new[] { "IDMenu" });
            DropIndex("dbo.tbUsuario", new[] { "IDEmpresa" });
            DropIndex("dbo.tbUsuario", new[] { "IDDepartamento" });
            DropIndex("dbo.tbUsuarioPerfil", new[] { "IDUsuario" });
            DropIndex("dbo.tbUsuarioPerfil", new[] { "IDPerfil" });
            RenameColumn(table: "dbo.tbMenu", name: "MenuSuperior_IDMenu", newName: "MenuSuperior_ID");
            RenameIndex(table: "dbo.tbMenu", name: "IX_MenuSuperior_IDMenu", newName: "IX_MenuSuperior_ID");
            DropPrimaryKey("dbo.tbAlocacao");
            DropPrimaryKey("dbo.tbContrato");
            DropPrimaryKey("dbo.tbDepartamento");
            DropPrimaryKey("dbo.tbEmpresa");
            DropPrimaryKey("dbo.tbFornecedor");
            DropPrimaryKey("dbo.tbEmpregado");
            DropPrimaryKey("dbo.tbEmpresaFornecedor");
            DropPrimaryKey("dbo.tbMenu");
            DropPrimaryKey("dbo.tbPerfil");
            DropPrimaryKey("dbo.tbPerfilMenu");
            DropPrimaryKey("dbo.tbUsuario");
            DropPrimaryKey("dbo.tbUsuarioPerfil");
            AddColumn("dbo.tbAlocacao", "ID", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.tbAlocacao", "Contrato_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbAlocacao", "Empregado_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbContrato", "ID", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.tbContrato", "Departamento_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbContrato", "Fornecedor_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbDepartamento", "ID", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.tbDepartamento", "Empresa_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbEmpresa", "ID", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.tbFornecedor", "ID", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.tbEmpregado", "ID", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.tbEmpregado", "Empresa_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbEmpregado", "Fornecedor_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbEmpresaFornecedor", "ID", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.tbEmpresaFornecedor", "Empresa_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbEmpresaFornecedor", "Fornecedor_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbMenu", "ID", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.tbPerfil", "ID", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.tbPerfilMenu", "ID", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.tbPerfilMenu", "Menu_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbPerfilMenu", "Perfil_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbUsuario", "ID", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.tbUsuario", "Departamento_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbUsuario", "Empresa_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbUsuarioPerfil", "ID", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.tbUsuarioPerfil", "Perfil_ID", c => c.String(maxLength: 128));
            AddColumn("dbo.tbUsuarioPerfil", "Usuario_ID", c => c.String(maxLength: 128));
            AlterColumn("dbo.tbAlocacao", "IDAlocacao", c => c.String());
            AlterColumn("dbo.tbContrato", "IDContrato", c => c.String());
            AlterColumn("dbo.tbDepartamento", "IDDepartamento", c => c.String());
            AlterColumn("dbo.tbEmpresa", "IDEmpresa", c => c.String());
            AlterColumn("dbo.tbFornecedor", "IDFornecedor", c => c.String());
            AlterColumn("dbo.tbEmpregado", "IDEmpregado", c => c.String());
            AlterColumn("dbo.tbEmpresaFornecedor", "IDEmpresaFornecedor", c => c.String());
            AlterColumn("dbo.tbMenu", "IDMenu", c => c.String());
            AlterColumn("dbo.tbPerfil", "IDPerfil", c => c.String());
            AlterColumn("dbo.tbPerfilMenu", "IDPerfilMenu", c => c.String());
            AlterColumn("dbo.tbUsuario", "IDUsuario", c => c.String());
            AlterColumn("dbo.tbUsuarioPerfil", "IDUsuarioPerfil", c => c.String());
            AddPrimaryKey("dbo.tbAlocacao", "ID");
            AddPrimaryKey("dbo.tbContrato", "ID");
            AddPrimaryKey("dbo.tbDepartamento", "ID");
            AddPrimaryKey("dbo.tbEmpresa", "ID");
            AddPrimaryKey("dbo.tbFornecedor", "ID");
            AddPrimaryKey("dbo.tbEmpregado", "ID");
            AddPrimaryKey("dbo.tbEmpresaFornecedor", "ID");
            AddPrimaryKey("dbo.tbMenu", "ID");
            AddPrimaryKey("dbo.tbPerfil", "ID");
            AddPrimaryKey("dbo.tbPerfilMenu", "ID");
            AddPrimaryKey("dbo.tbUsuario", "ID");
            AddPrimaryKey("dbo.tbUsuarioPerfil", "ID");
            CreateIndex("dbo.tbAlocacao", "Contrato_ID");
            CreateIndex("dbo.tbAlocacao", "Empregado_ID");
            CreateIndex("dbo.tbContrato", "Departamento_ID");
            CreateIndex("dbo.tbContrato", "Fornecedor_ID");
            CreateIndex("dbo.tbDepartamento", "Empresa_ID");
            CreateIndex("dbo.tbEmpregado", "Empresa_ID");
            CreateIndex("dbo.tbEmpregado", "Fornecedor_ID");
            CreateIndex("dbo.tbEmpresaFornecedor", "Empresa_ID");
            CreateIndex("dbo.tbEmpresaFornecedor", "Fornecedor_ID");
            CreateIndex("dbo.tbPerfilMenu", "Menu_ID");
            CreateIndex("dbo.tbPerfilMenu", "Perfil_ID");
            CreateIndex("dbo.tbUsuario", "Departamento_ID");
            CreateIndex("dbo.tbUsuario", "Empresa_ID");
            CreateIndex("dbo.tbUsuarioPerfil", "Perfil_ID");
            CreateIndex("dbo.tbUsuarioPerfil", "Usuario_ID");
            AddForeignKey("dbo.tbAlocacao", "Contrato_ID", "dbo.tbContrato", "ID");
            AddForeignKey("dbo.tbAlocacao", "Empregado_ID", "dbo.tbEmpregado", "ID");
            AddForeignKey("dbo.tbContrato", "Departamento_ID", "dbo.tbDepartamento", "ID");
            AddForeignKey("dbo.tbContrato", "Fornecedor_ID", "dbo.tbFornecedor", "ID");
            AddForeignKey("dbo.tbDepartamento", "Empresa_ID", "dbo.tbEmpresa", "ID");
            AddForeignKey("dbo.tbEmpregado", "Empresa_ID", "dbo.tbEmpresa", "ID");
            AddForeignKey("dbo.tbEmpregado", "Fornecedor_ID", "dbo.tbFornecedor", "ID");
            AddForeignKey("dbo.tbEmpresaFornecedor", "Empresa_ID", "dbo.tbEmpresa", "ID");
            AddForeignKey("dbo.tbEmpresaFornecedor", "Fornecedor_ID", "dbo.tbFornecedor", "ID");
            AddForeignKey("dbo.tbPerfilMenu", "Menu_ID", "dbo.tbMenu", "ID");
            AddForeignKey("dbo.tbPerfilMenu", "Perfil_ID", "dbo.tbPerfil", "ID");
            AddForeignKey("dbo.tbUsuario", "Departamento_ID", "dbo.tbDepartamento", "ID");
            AddForeignKey("dbo.tbUsuario", "Empresa_ID", "dbo.tbEmpresa", "ID");
            AddForeignKey("dbo.tbUsuarioPerfil", "Perfil_ID", "dbo.tbPerfil", "ID");
            AddForeignKey("dbo.tbUsuarioPerfil", "Usuario_ID", "dbo.tbUsuario", "ID");
            AddForeignKey("dbo.tbMenu", "MenuSuperior_ID", "dbo.tbMenu", "ID");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.tbMenu", "MenuSuperior_ID", "dbo.tbMenu");
            DropForeignKey("dbo.tbUsuarioPerfil", "Usuario_ID", "dbo.tbUsuario");
            DropForeignKey("dbo.tbUsuarioPerfil", "Perfil_ID", "dbo.tbPerfil");
            DropForeignKey("dbo.tbUsuario", "Empresa_ID", "dbo.tbEmpresa");
            DropForeignKey("dbo.tbUsuario", "Departamento_ID", "dbo.tbDepartamento");
            DropForeignKey("dbo.tbPerfilMenu", "Perfil_ID", "dbo.tbPerfil");
            DropForeignKey("dbo.tbPerfilMenu", "Menu_ID", "dbo.tbMenu");
            DropForeignKey("dbo.tbEmpresaFornecedor", "Fornecedor_ID", "dbo.tbFornecedor");
            DropForeignKey("dbo.tbEmpresaFornecedor", "Empresa_ID", "dbo.tbEmpresa");
            DropForeignKey("dbo.tbEmpregado", "Fornecedor_ID", "dbo.tbFornecedor");
            DropForeignKey("dbo.tbEmpregado", "Empresa_ID", "dbo.tbEmpresa");
            DropForeignKey("dbo.tbDepartamento", "Empresa_ID", "dbo.tbEmpresa");
            DropForeignKey("dbo.tbContrato", "Fornecedor_ID", "dbo.tbFornecedor");
            DropForeignKey("dbo.tbContrato", "Departamento_ID", "dbo.tbDepartamento");
            DropForeignKey("dbo.tbAlocacao", "Empregado_ID", "dbo.tbEmpregado");
            DropForeignKey("dbo.tbAlocacao", "Contrato_ID", "dbo.tbContrato");
            DropIndex("dbo.tbUsuarioPerfil", new[] { "Usuario_ID" });
            DropIndex("dbo.tbUsuarioPerfil", new[] { "Perfil_ID" });
            DropIndex("dbo.tbUsuario", new[] { "Empresa_ID" });
            DropIndex("dbo.tbUsuario", new[] { "Departamento_ID" });
            DropIndex("dbo.tbPerfilMenu", new[] { "Perfil_ID" });
            DropIndex("dbo.tbPerfilMenu", new[] { "Menu_ID" });
            DropIndex("dbo.tbEmpresaFornecedor", new[] { "Fornecedor_ID" });
            DropIndex("dbo.tbEmpresaFornecedor", new[] { "Empresa_ID" });
            DropIndex("dbo.tbEmpregado", new[] { "Fornecedor_ID" });
            DropIndex("dbo.tbEmpregado", new[] { "Empresa_ID" });
            DropIndex("dbo.tbDepartamento", new[] { "Empresa_ID" });
            DropIndex("dbo.tbContrato", new[] { "Fornecedor_ID" });
            DropIndex("dbo.tbContrato", new[] { "Departamento_ID" });
            DropIndex("dbo.tbAlocacao", new[] { "Empregado_ID" });
            DropIndex("dbo.tbAlocacao", new[] { "Contrato_ID" });
            DropPrimaryKey("dbo.tbUsuarioPerfil");
            DropPrimaryKey("dbo.tbUsuario");
            DropPrimaryKey("dbo.tbPerfilMenu");
            DropPrimaryKey("dbo.tbPerfil");
            DropPrimaryKey("dbo.tbMenu");
            DropPrimaryKey("dbo.tbEmpresaFornecedor");
            DropPrimaryKey("dbo.tbEmpregado");
            DropPrimaryKey("dbo.tbFornecedor");
            DropPrimaryKey("dbo.tbEmpresa");
            DropPrimaryKey("dbo.tbDepartamento");
            DropPrimaryKey("dbo.tbContrato");
            DropPrimaryKey("dbo.tbAlocacao");
            AlterColumn("dbo.tbUsuarioPerfil", "IDUsuarioPerfil", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.tbUsuario", "IDUsuario", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.tbPerfilMenu", "IDPerfilMenu", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.tbPerfil", "IDPerfil", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.tbMenu", "IDMenu", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.tbEmpresaFornecedor", "IDEmpresaFornecedor", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.tbEmpregado", "IDEmpregado", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.tbFornecedor", "IDFornecedor", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.tbEmpresa", "IDEmpresa", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.tbDepartamento", "IDDepartamento", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.tbContrato", "IDContrato", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.tbAlocacao", "IDAlocacao", c => c.String(nullable: false, maxLength: 128));
            DropColumn("dbo.tbUsuarioPerfil", "Usuario_ID");
            DropColumn("dbo.tbUsuarioPerfil", "Perfil_ID");
            DropColumn("dbo.tbUsuarioPerfil", "ID");
            DropColumn("dbo.tbUsuario", "Empresa_ID");
            DropColumn("dbo.tbUsuario", "Departamento_ID");
            DropColumn("dbo.tbUsuario", "ID");
            DropColumn("dbo.tbPerfilMenu", "Perfil_ID");
            DropColumn("dbo.tbPerfilMenu", "Menu_ID");
            DropColumn("dbo.tbPerfilMenu", "ID");
            DropColumn("dbo.tbPerfil", "ID");
            DropColumn("dbo.tbMenu", "ID");
            DropColumn("dbo.tbEmpresaFornecedor", "Fornecedor_ID");
            DropColumn("dbo.tbEmpresaFornecedor", "Empresa_ID");
            DropColumn("dbo.tbEmpresaFornecedor", "ID");
            DropColumn("dbo.tbEmpregado", "Fornecedor_ID");
            DropColumn("dbo.tbEmpregado", "Empresa_ID");
            DropColumn("dbo.tbEmpregado", "ID");
            DropColumn("dbo.tbFornecedor", "ID");
            DropColumn("dbo.tbEmpresa", "ID");
            DropColumn("dbo.tbDepartamento", "Empresa_ID");
            DropColumn("dbo.tbDepartamento", "ID");
            DropColumn("dbo.tbContrato", "Fornecedor_ID");
            DropColumn("dbo.tbContrato", "Departamento_ID");
            DropColumn("dbo.tbContrato", "ID");
            DropColumn("dbo.tbAlocacao", "Empregado_ID");
            DropColumn("dbo.tbAlocacao", "Contrato_ID");
            DropColumn("dbo.tbAlocacao", "ID");
            AddPrimaryKey("dbo.tbUsuarioPerfil", "IDUsuarioPerfil");
            AddPrimaryKey("dbo.tbUsuario", "IDUsuario");
            AddPrimaryKey("dbo.tbPerfilMenu", "IDPerfilMenu");
            AddPrimaryKey("dbo.tbPerfil", "IDPerfil");
            AddPrimaryKey("dbo.tbMenu", "IDMenu");
            AddPrimaryKey("dbo.tbEmpresaFornecedor", "IDEmpresaFornecedor");
            AddPrimaryKey("dbo.tbEmpregado", "IDEmpregado");
            AddPrimaryKey("dbo.tbFornecedor", "IDFornecedor");
            AddPrimaryKey("dbo.tbEmpresa", "IDEmpresa");
            AddPrimaryKey("dbo.tbDepartamento", "IDDepartamento");
            AddPrimaryKey("dbo.tbContrato", "IDContrato");
            AddPrimaryKey("dbo.tbAlocacao", "IDAlocacao");
            RenameIndex(table: "dbo.tbMenu", name: "IX_MenuSuperior_ID", newName: "IX_MenuSuperior_IDMenu");
            RenameColumn(table: "dbo.tbMenu", name: "MenuSuperior_ID", newName: "MenuSuperior_IDMenu");
            CreateIndex("dbo.tbUsuarioPerfil", "IDPerfil");
            CreateIndex("dbo.tbUsuarioPerfil", "IDUsuario");
            CreateIndex("dbo.tbUsuario", "IDDepartamento");
            CreateIndex("dbo.tbUsuario", "IDEmpresa");
            CreateIndex("dbo.tbPerfilMenu", "IDMenu");
            CreateIndex("dbo.tbPerfilMenu", "IDPerfil");
            CreateIndex("dbo.tbEmpresaFornecedor", "IDFornecedor");
            CreateIndex("dbo.tbEmpresaFornecedor", "IDEmpresa");
            CreateIndex("dbo.tbEmpregado", "IDFornecedor");
            CreateIndex("dbo.tbEmpregado", "IDEmpresa");
            CreateIndex("dbo.tbDepartamento", "IDEmpresa");
            CreateIndex("dbo.tbContrato", "IDDepartamento");
            CreateIndex("dbo.tbContrato", "IDFornecedor");
            CreateIndex("dbo.tbAlocacao", "IDContrato");
            CreateIndex("dbo.tbAlocacao", "IDEmpregado");
            AddForeignKey("dbo.tbMenu", "MenuSuperior_IDMenu", "dbo.tbMenu", "IDMenu");
            AddForeignKey("dbo.tbUsuarioPerfil", "IDUsuario", "dbo.tbUsuario", "IDUsuario", cascadeDelete: true);
            AddForeignKey("dbo.tbUsuarioPerfil", "IDPerfil", "dbo.tbPerfil", "IDPerfil", cascadeDelete: true);
            AddForeignKey("dbo.tbUsuario", "IDEmpresa", "dbo.tbEmpresa", "IDEmpresa", cascadeDelete: true);
            AddForeignKey("dbo.tbUsuario", "IDDepartamento", "dbo.tbDepartamento", "IDDepartamento", cascadeDelete: true);
            AddForeignKey("dbo.tbPerfilMenu", "IDPerfil", "dbo.tbPerfil", "IDPerfil", cascadeDelete: true);
            AddForeignKey("dbo.tbPerfilMenu", "IDMenu", "dbo.tbMenu", "IDMenu", cascadeDelete: true);
            AddForeignKey("dbo.tbEmpresaFornecedor", "IDFornecedor", "dbo.tbFornecedor", "IDFornecedor", cascadeDelete: true);
            AddForeignKey("dbo.tbEmpresaFornecedor", "IDEmpresa", "dbo.tbEmpresa", "IDEmpresa", cascadeDelete: true);
            AddForeignKey("dbo.tbEmpregado", "IDFornecedor", "dbo.tbFornecedor", "IDFornecedor");
            AddForeignKey("dbo.tbEmpregado", "IDEmpresa", "dbo.tbEmpresa", "IDEmpresa");
            AddForeignKey("dbo.tbDepartamento", "IDEmpresa", "dbo.tbEmpresa", "IDEmpresa", cascadeDelete: true);
            AddForeignKey("dbo.tbContrato", "IDFornecedor", "dbo.tbFornecedor", "IDFornecedor", cascadeDelete: true);
            AddForeignKey("dbo.tbContrato", "IDDepartamento", "dbo.tbDepartamento", "IDDepartamento", cascadeDelete: true);
            AddForeignKey("dbo.tbAlocacao", "IDEmpregado", "dbo.tbEmpregado", "IDEmpregado", cascadeDelete: true);
            AddForeignKey("dbo.tbAlocacao", "IDContrato", "dbo.tbContrato", "IDContrato", cascadeDelete: true);
        }
    }
}
